repos:
  - repo: local
    hooks:
      - id: generate-api-spec
        name: Generate API Spec
        entry: make generate.api-spec
        language: system
        fail_fast: true
        pass_filenames: false
        stages: [pre-commit]
