basePath: /api/v1
definitions:
  main.ErrorResponse:
    properties:
      code:
        type: integer
    type: object
  main.Response:
    properties:
      message:
        type: string
      status:
        type: integer
    type: object
  main.response:
    properties:
      message:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8082
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API echo
  version: "1.0"
paths:
  /examples:
    delete:
      consumes:
      - application/json
      description: Deletes an example resource
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.response'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete an example
      tags:
      - examples
    get:
      consumes:
      - application/json
      description: |-
        ### cURL Example

        ```bash
        curl -X GET "http://localhost/api/v1/example" -H "Accept: application/json"
        ```

        Returns an example resource
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.ErrorResponse'
      summary: Get an example
      tags:
      - internal
    post:
      consumes:
      - application/json
      description: Creates a new example resource
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create an example
      tags:
      - internal
    put:
      consumes:
      - application/json
      description: Updates an example resource
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update an example
      tags:
      - internal
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
